<a href="https://colab.research.google.com/github/hafsakhaerunisa/DATA_SKRIPSI/blob/main/OPTricluster_Hafsa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#STANDARDISASI DATA KA DEA

In [ ]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Membaca data ekspresi gen 3D dari file CSV
data= pd.read_csv('https://raw.githubusercontent.com/hafsakhaerunisa/Data_Skripsi_Dea/main/Data_YF_Dea.csv', delimiter=';')
df=pd.DataFrame(data)
df


ID_REF      F1_D3      F1_D7     F1_D14     F1_D84      F2_D3  \
0      ILMN_1343291  14.182451  13.592888  13.620552  13.831521  13.744493   
1      ILMN_1343295   9.986925  10.273344  10.079217  10.230349  10.632209   
2      ILMN_1651199   6.554642   6.490022   6.550121   6.668063   6.507411   
3      ILMN_1651209   6.572533   6.671103   6.483453   6.591966   6.442771   
4      ILMN_1651210   6.674431   6.593931   7.058900   6.684124   6.782176   
...             ...        ...        ...        ...        ...        ...   
47318  ILMN_3311170   6.456507   6.533727   6.527950   6.517199   6.507411   
47319  ILMN_3311175   6.516818   6.512122   6.550121   6.591966   6.523779   
47320  ILMN_3311180   6.608175   6.445151   7.109790   6.731542   6.743798   
47321  ILMN_3311185   6.590464   6.613130   6.505434   6.715576   6.706714   
47322  ILMN_3311190   6.590464   6.671103   6.611905   6.547935   6.639206   

           F2_D7     F2_D14     F2_D84      M1_D3      M1_D7     M1_D14  \
0      13.868905  13.421753  13.818026  14.328031  14.063495  13.908427   
1      10.542389  10.521745  10.530151   9.854798   9.838299  10.173844   
2       6.403978   6.619135   6.504005   6.513215   6.473376   6.739319   
3       6.528221   6.520194   6.521444   6.657767   6.639457   6.658310   
4       6.603511   6.710389   6.590205   6.513215   6.538998   6.718234   
...          ...        ...        ...        ...        ...        ...   
47318   6.573110   6.569383   6.504005   6.491021   6.496228   6.601250   
47319   6.603511   6.619135   6.468987   6.357643   6.496228   6.464698   
47320   6.757520   6.644231   6.796730   6.657767   6.695054   6.718234   
47321   6.573110   6.532919   6.572690   6.491021   6.378854   6.442829   
47322   6.588546   6.606332   6.640908   6.745381   6.783536   6.464698   

          M1_D84      M2_D3      M2_D7     M2_D14     M2_D84  
0      13.977382  14.284968  13.574826  13.868905  14.249150  
1      10.095630  10.149738  10.318613  10.681152  10.282367  
2       6.635997   6.473095   6.362111   6.592017   6.467634  
3       6.365566   6.688777   6.468198   6.688486   6.635068  
4       6.779702   6.405156   6.492186   6.550707   6.579649  
...          ...        ...        ...        ...        ...  
47318   6.518534   6.534697   6.561846   6.505434   6.593000  
47319   6.705471   6.658014   6.492186   6.505434   6.552729  
47320   6.534104   6.451582   6.623647   6.571589   6.496228  
47321   6.518534   6.607919   6.389164   6.284698   6.538246  
47322   6.426903   6.717238   6.583402   6.688486   6.579649  

[47323 rows x 17 columns]

In [ ]:
# Menghapus kolom yang tidak diperlukan, seperti ID pasien atau waktu pengambilan sampel
df2 = df.iloc[:,1:]
df2

F1_D3      F1_D7     F1_D14     F1_D84      F2_D3      F2_D7  \
0      14.182451  13.592888  13.620552  13.831521  13.744493  13.868905   
1       9.986925  10.273344  10.079217  10.230349  10.632209  10.542389   
2       6.554642   6.490022   6.550121   6.668063   6.507411   6.403978   
3       6.572533   6.671103   6.483453   6.591966   6.442771   6.528221   
4       6.674431   6.593931   7.058900   6.684124   6.782176   6.603511   
...          ...        ...        ...        ...        ...        ...   
47318   6.456507   6.533727   6.527950   6.517199   6.507411   6.573110   
47319   6.516818   6.512122   6.550121   6.591966   6.523779   6.603511   
47320   6.608175   6.445151   7.109790   6.731542   6.743798   6.757520   
47321   6.590464   6.613130   6.505434   6.715576   6.706714   6.573110   
47322   6.590464   6.671103   6.611905   6.547935   6.639206   6.588546   

          F2_D14     F2_D84      M1_D3      M1_D7     M1_D14     M1_D84  \
0      13.421753  13.818026  14.328031  14.063495  13.908427  13.977382   
1      10.521745  10.530151   9.854798   9.838299  10.173844  10.095630   
2       6.619135   6.504005   6.513215   6.473376   6.739319   6.635997   
3       6.520194   6.521444   6.657767   6.639457   6.658310   6.365566   
4       6.710389   6.590205   6.513215   6.538998   6.718234   6.779702   
...          ...        ...        ...        ...        ...        ...   
47318   6.569383   6.504005   6.491021   6.496228   6.601250   6.518534   
47319   6.619135   6.468987   6.357643   6.496228   6.464698   6.705471   
47320   6.644231   6.796730   6.657767   6.695054   6.718234   6.534104   
47321   6.532919   6.572690   6.491021   6.378854   6.442829   6.518534   
47322   6.606332   6.640908   6.745381   6.783536   6.464698   6.426903   

           M2_D3      M2_D7     M2_D14     M2_D84  
0      14.284968  13.574826  13.868905  14.249150  
1      10.149738  10.318613  10.681152  10.282367  
2       6.473095   6.362111   6.592017   6.467634  
3       6.688777   6.468198   6.688486   6.635068  
4       6.405156   6.492186   6.550707   6.579649  
...          ...        ...        ...        ...  
47318   6.534697   6.561846   6.505434   6.593000  
47319   6.658014   6.492186   6.505434   6.552729  
47320   6.451582   6.623647   6.571589   6.496228  
47321   6.607919   6.389164   6.284698   6.538246  
47322   6.717238   6.583402   6.688486   6.579649  

[47323 rows x 16 columns]

In [ ]:
# Mengisi nilai yang hilang (jika ada) dengan nilai rata-rata kolom
df2 = df2.fillna(df2.mean())

#Normalize Data
import numpy as np
from sklearn import preprocessing

data3 = np.copy(df2)

In [ ]:
# Standardisasi data dengan modul StandardScaler
scaler = StandardScaler()
df_standardized = scaler.fit_transform(data3)
df_standardized

array([[ 7.85005802,  7.21349411,  7.24340362, ...,  7.19393522,
         7.51143492,  7.92217125],
       [ 3.3195478 ,  3.62888354,  3.41926189, ...,  3.67771719,
         4.06918608,  3.63856986],
       [-0.3867787 , -0.4565379 , -0.39166339, ..., -0.59470855,
        -0.34640574, -0.48083805],
       ...,
       [-0.32897156, -0.50499143,  0.21270008, ..., -0.31228837,
        -0.36846528, -0.44995967],
       [-0.34809649, -0.32359933, -0.43991919, ..., -0.56549476,
        -0.67825988, -0.40458615],
       [-0.34809649, -0.26099669, -0.32494486, ..., -0.35574768,
        -0.24223509, -0.3598767 ]])

In [ ]:
df_std=pd.DataFrame(df_standardized, columns=df2.columns)
df_std

F1_D3     F1_D7    F1_D14    F1_D84     F2_D3     F2_D7    F2_D14  \
0      7.850058  7.213494  7.243404  7.471119  7.377140  7.511430  7.028431   
1      3.319548  3.628884  3.419262  3.582409  4.016372  3.919331  3.896984   
2     -0.386779 -0.456538 -0.391663 -0.264310 -0.437749 -0.549484 -0.317078   
3     -0.367459 -0.260997 -0.463655 -0.346484 -0.507549 -0.415321 -0.423915   
4     -0.257426 -0.344332  0.157746 -0.246967 -0.141046 -0.334020 -0.218541   
...         ...       ...       ...       ...       ...       ...       ...   
47318 -0.492749 -0.409342 -0.415604 -0.427220 -0.437749 -0.366848 -0.370801   
47319 -0.427623 -0.432673 -0.391663 -0.346484 -0.420074 -0.334020 -0.317078   
47320 -0.328972 -0.504991  0.212700 -0.195763 -0.182489 -0.167715 -0.289980   
47321 -0.348096 -0.323599 -0.439919 -0.213003 -0.222534 -0.366848 -0.410175   
47322 -0.348096 -0.260997 -0.324945 -0.394030 -0.295431 -0.350180 -0.330903   

         F2_D84     M1_D3     M1_D7    M1_D14    M1_D84     M2_D3     M2_D7  \
0      7.456443  8.007367  7.721676  7.554332  7.628543  7.960735  7.193935   
1      3.906114  3.176878  3.159080  3.521458  3.436908  3.495338  3.677717   
2     -0.441419 -0.431581 -0.474547 -0.187390 -0.298910 -0.474858 -0.594709   
3     -0.422587 -0.275485 -0.295204 -0.274869 -0.590931 -0.241955 -0.480151   
4     -0.348338 -0.431581 -0.403684 -0.210160 -0.143733 -0.548221 -0.454247   
...         ...       ...       ...       ...       ...       ...       ...   
47318 -0.441419 -0.455548 -0.449869 -0.336487 -0.425751 -0.408337 -0.379024   
47319 -0.479232 -0.599578 -0.449869 -0.483946 -0.223890 -0.275174 -0.454247   
47320 -0.125327 -0.275485 -0.235167 -0.210160 -0.408937 -0.498088 -0.312288   
47321 -0.367250 -0.455548 -0.576617 -0.507562 -0.425751 -0.329269 -0.565495   
47322 -0.293587 -0.180874 -0.139618 -0.483946 -0.524697 -0.211222 -0.355748   

         M2_D14    M2_D84  
0      7.511435  7.922171  
1      4.069186  3.638570  
2     -0.346406 -0.480838  
3     -0.242235 -0.300031  
4     -0.391014 -0.359877  
...         ...       ...  
47318 -0.439902 -0.345459  
47319 -0.439902 -0.388947  
47320 -0.368465 -0.449960  
47321 -0.678260 -0.404586  
47322 -0.242235 -0.359877  

[47323 rows x 16 columns]

##Female dan Male Data Pertama Dituker

In [ ]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Membaca data ekspresi gen 3D dari file CSV
data_baru= pd.read_csv('https://raw.githubusercontent.com/hafsakhaerunisa/Data_Skripsi_Dea/main/data_skripsi_dea.csv', delimiter=';')
df_baru=pd.DataFrame(data_baru)
df_baru

ID_REF      F2_D3      F2_D7     F2_D14     F2_D84      F1_D3  \
0      ILMN_1343291  13.744493  13.868905  13.421753  13.818026  14.182451   
1      ILMN_1343295  10.632209  10.542389  10.521745  10.530151   9.986925   
2      ILMN_1651199   6.507411   6.403978   6.619135   6.504005   6.554642   
3      ILMN_1651209   6.442771   6.528221   6.520194   6.521444   6.572533   
4      ILMN_1651210   6.782176   6.603511   6.710389   6.590205   6.674431   
...             ...        ...        ...        ...        ...        ...   
47318  ILMN_3311170   6.507411   6.573110   6.569383   6.504005   6.456507   
47319  ILMN_3311175   6.523779   6.603511   6.619135   6.468987   6.516818   
47320  ILMN_3311180   6.743798   6.757520   6.644231   6.796730   6.608175   
47321  ILMN_3311185   6.706714   6.573110   6.532919   6.572690   6.590464   
47322  ILMN_3311190   6.639206   6.588546   6.606332   6.640908   6.590464   

           F1_D7     F1_D14     F1_D84      M2_D3      M2_D7     M2_D14  \
0      13.592888  13.620552  13.831521  14.284968  13.574826  13.868905   
1      10.273344  10.079217  10.230349  10.149738  10.318613  10.681152   
2       6.490022   6.550121   6.668063   6.473095   6.362111   6.592017   
3       6.671103   6.483453   6.591966   6.688777   6.468198   6.688486   
4       6.593931   7.058900   6.684124   6.405156   6.492186   6.550707   
...          ...        ...        ...        ...        ...        ...   
47318   6.533727   6.527950   6.517199   6.534697   6.561846   6.505434   
47319   6.512122   6.550121   6.591966   6.658014   6.492186   6.505434   
47320   6.445151   7.109790   6.731542   6.451582   6.623647   6.571589   
47321   6.613130   6.505434   6.715576   6.607919   6.389164   6.284698   
47322   6.671103   6.611905   6.547935   6.717238   6.583402   6.688486   

          M2_D84      M1_D3      M1_D7     M1_D14     M1_D84  
0      14.249150  14.328031  14.063495  13.908427  13.977382  
1      10.282367   9.854798   9.838299  10.173844  10.095630  
2       6.467634   6.513215   6.473376   6.739319   6.635997  
3       6.635068   6.657767   6.639457   6.658310   6.365566  
4       6.579649   6.513215   6.538998   6.718234   6.779702  
...          ...        ...        ...        ...        ...  
47318   6.593000   6.491021   6.496228   6.601250   6.518534  
47319   6.552729   6.357643   6.496228   6.464698   6.705471  
47320   6.496228   6.657767   6.695054   6.718234   6.534104  
47321   6.538246   6.491021   6.378854   6.442829   6.518534  
47322   6.579649   6.745381   6.783536   6.464698   6.426903  

[47323 rows x 17 columns]

In [ ]:
# Menghapus kolom yang tidak diperlukan, seperti ID pasien atau waktu pengambilan sampel
df2_baru = df_baru.iloc[:,1:]
df2_baru


F2_D3      F2_D7     F2_D14     F2_D84      F1_D3      F1_D7  \
0      13.744493  13.868905  13.421753  13.818026  14.182451  13.592888   
1      10.632209  10.542389  10.521745  10.530151   9.986925  10.273344   
2       6.507411   6.403978   6.619135   6.504005   6.554642   6.490022   
3       6.442771   6.528221   6.520194   6.521444   6.572533   6.671103   
4       6.782176   6.603511   6.710389   6.590205   6.674431   6.593931   
...          ...        ...        ...        ...        ...        ...   
47318   6.507411   6.573110   6.569383   6.504005   6.456507   6.533727   
47319   6.523779   6.603511   6.619135   6.468987   6.516818   6.512122   
47320   6.743798   6.757520   6.644231   6.796730   6.608175   6.445151   
47321   6.706714   6.573110   6.532919   6.572690   6.590464   6.613130   
47322   6.639206   6.588546   6.606332   6.640908   6.590464   6.671103   

          F1_D14     F1_D84      M2_D3      M2_D7     M2_D14     M2_D84  \
0      13.620552  13.831521  14.284968  13.574826  13.868905  14.249150   
1      10.079217  10.230349  10.149738  10.318613  10.681152  10.282367   
2       6.550121   6.668063   6.473095   6.362111   6.592017   6.467634   
3       6.483453   6.591966   6.688777   6.468198   6.688486   6.635068   
4       7.058900   6.684124   6.405156   6.492186   6.550707   6.579649   
...          ...        ...        ...        ...        ...        ...   
47318   6.527950   6.517199   6.534697   6.561846   6.505434   6.593000   
47319   6.550121   6.591966   6.658014   6.492186   6.505434   6.552729   
47320   7.109790   6.731542   6.451582   6.623647   6.571589   6.496228   
47321   6.505434   6.715576   6.607919   6.389164   6.284698   6.538246   
47322   6.611905   6.547935   6.717238   6.583402   6.688486   6.579649   

           M1_D3      M1_D7     M1_D14     M1_D84  
0      14.328031  14.063495  13.908427  13.977382  
1       9.854798   9.838299  10.173844  10.095630  
2       6.513215   6.473376   6.739319   6.635997  
3       6.657767   6.639457   6.658310   6.365566  
4       6.513215   6.538998   6.718234   6.779702  
...          ...        ...        ...        ...  
47318   6.491021   6.496228   6.601250   6.518534  
47319   6.357643   6.496228   6.464698   6.705471  
47320   6.657767   6.695054   6.718234   6.534104  
47321   6.491021   6.378854   6.442829   6.518534  
47322   6.745381   6.783536   6.464698   6.426903  

[47323 rows x 16 columns]

In [ ]:
# Mengisi nilai yang hilang (jika ada) dengan nilai rata-rata kolom
df2_baru = df2_baru.fillna(df2.mean())

#Normalize Data
import numpy as np
from sklearn import preprocessing

data3_baru = np.copy(df2_baru)

# Standardisasi data dengan modul StandardScaler
scaler2 = StandardScaler()
df2_baru_standardized = scaler2.fit_transform(data3_baru)
df2_baru_standardized

array([[ 7.37714007,  7.51142973,  7.0284314 , ...,  7.72167599,
         7.55433212,  7.62854305],
       [ 4.01637227,  3.91933089,  3.89698433, ...,  3.15907989,
         3.52145836,  3.43690753],
       [-0.43774942, -0.54948374, -0.31707813, ..., -0.47454662,
        -0.18739   , -0.29891017],
       ...,
       [-0.18248907, -0.16771549, -0.28997953, ..., -0.23516676,
        -0.21015983, -0.40893746],
       [-0.22253357, -0.36684832, -0.41017473, ..., -0.57661675,
        -0.507562  , -0.42575066],
       [-0.29543135, -0.35017975, -0.33090309, ..., -0.13961828,
        -0.48394635, -0.52469655]])

In [ ]:
df2_baru_std=pd.DataFrame(df2_baru_standardized,columns=df2_baru.columns)
df2_baru_std

F2_D3     F2_D7    F2_D14    F2_D84     F1_D3     F1_D7    F1_D14  \
0      7.377140  7.511430  7.028431  7.456443  7.850058  7.213494  7.243404   
1      4.016372  3.919331  3.896984  3.906114  3.319548  3.628884  3.419262   
2     -0.437749 -0.549484 -0.317078 -0.441419 -0.386779 -0.456538 -0.391663   
3     -0.507549 -0.415321 -0.423915 -0.422587 -0.367459 -0.260997 -0.463655   
4     -0.141046 -0.334020 -0.218541 -0.348338 -0.257426 -0.344332  0.157746   
...         ...       ...       ...       ...       ...       ...       ...   
47318 -0.437749 -0.366848 -0.370801 -0.441419 -0.492749 -0.409342 -0.415604   
47319 -0.420074 -0.334020 -0.317078 -0.479232 -0.427623 -0.432673 -0.391663   
47320 -0.182489 -0.167715 -0.289980 -0.125327 -0.328972 -0.504991  0.212700   
47321 -0.222534 -0.366848 -0.410175 -0.367250 -0.348096 -0.323599 -0.439919   
47322 -0.295431 -0.350180 -0.330903 -0.293587 -0.348096 -0.260997 -0.324945   

         F1_D84     M2_D3     M2_D7    M2_D14    M2_D84     M1_D3     M1_D7  \
0      7.471119  7.960735  7.193935  7.511435  7.922171  8.007367  7.721676   
1      3.582409  3.495338  3.677717  4.069186  3.638570  3.176878  3.159080   
2     -0.264310 -0.474858 -0.594709 -0.346406 -0.480838 -0.431581 -0.474547   
3     -0.346484 -0.241955 -0.480151 -0.242235 -0.300031 -0.275485 -0.295204   
4     -0.246967 -0.548221 -0.454247 -0.391014 -0.359877 -0.431581 -0.403684   
...         ...       ...       ...       ...       ...       ...       ...   
47318 -0.427220 -0.408337 -0.379024 -0.439902 -0.345459 -0.455548 -0.449869   
47319 -0.346484 -0.275174 -0.454247 -0.439902 -0.388947 -0.599578 -0.449869   
47320 -0.195763 -0.498088 -0.312288 -0.368465 -0.449960 -0.275485 -0.235167   
47321 -0.213003 -0.329269 -0.565495 -0.678260 -0.404586 -0.455548 -0.576617   
47322 -0.394030 -0.211222 -0.355748 -0.242235 -0.359877 -0.180874 -0.139618   

         M1_D14    M1_D84  
0      7.554332  7.628543  
1      3.521458  3.436908  
2     -0.187390 -0.298910  
3     -0.274869 -0.590931  
4     -0.210160 -0.143733  
...         ...       ...  
47318 -0.336487 -0.425751  
47319 -0.483946 -0.223890  
47320 -0.210160 -0.408937  
47321 -0.507562 -0.425751  
47322 -0.483946 -0.524697  

[47323 rows x 16 columns]

#MATRIKS KUANTISASI KA DEA

#MATRIKS DATA HAFSA

##LANGKAH 1 (menstandardisasi dan normalisasi data)

In [16]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Membaca data ekspresi gen 3D dari file CSV
data1= pd.read_csv('https://raw.githubusercontent.com/hafsakhaerunisa/DATA_SKRIPSI/main/Data_aslicaca.csv', delimiter=';')
df1=pd.DataFrame(data)
df1

ID_REF      A_6_h     A_24_h     A_48_h      J_6_h     J_24_h  \
0            1007_s_at  10.821314  10.649540  11.109125  10.580838  10.471660   
1              1053_at   9.136269   9.582176   8.885379   9.249496   9.506714   
2               117_at   6.240821   5.723533   5.444779   5.360860   5.058175   
3               121_at   8.139956   7.984728   8.025075   7.720294   7.926594   
4            1255_g_at   3.068877   3.031040   2.923666   3.022046   3.030927   
...                ...        ...        ...        ...        ...        ...   
54670   AFFX-ThrX-5_at   5.297636   5.566142   5.472700   5.762386   4.963139   
54671   AFFX-ThrX-M_at   5.253165   5.978144   5.889662   6.222809   4.792429   
54672  AFFX-TrpnX-3_at   2.592453   2.700229   2.656674   2.719876   2.608102   
54673  AFFX-TrpnX-5_at   3.340522   3.633973   3.265097   3.625882   3.477362   
54674  AFFX-TrpnX-M_at   2.932932   3.271605   2.856124   2.958953   2.874971   

          J_48_h     AJ_6_h   AJ_24_h   AJ_48_h  
0      10.620836  10.223919  9.710350  9.465731  
1       8.808796   9.000807  9.152421  9.467526  
2       4.998387   8.169325  6.049426  5.657824  
3       8.077343   7.859269  8.060785  8.116295  
4       2.833551   2.961509  2.897476  3.059194  
...          ...        ...       ...       ...  
54670   5.634883   5.905186  5.537162  5.742731  
54671   6.156076   6.191868  5.819676  6.084831  
54672   3.063190   2.645845  2.834575  2.638259  
54673   3.603461   3.616770  3.500324  3.598264  
54674   2.932881   3.031149  2.981076  2.915787  

[54675 rows x 10 columns]

In [17]:
# Menghapus kolom yang tidak diperlukan, seperti ID pasien atau waktu pengambilan sampel
df2 = df1.iloc[:,1:]
df2

A_6_h     A_24_h     A_48_h      J_6_h     J_24_h     J_48_h  \
0      10.821314  10.649540  11.109125  10.580838  10.471660  10.620836   
1       9.136269   9.582176   8.885379   9.249496   9.506714   8.808796   
2       6.240821   5.723533   5.444779   5.360860   5.058175   4.998387   
3       8.139956   7.984728   8.025075   7.720294   7.926594   8.077343   
4       3.068877   3.031040   2.923666   3.022046   3.030927   2.833551   
...          ...        ...        ...        ...        ...        ...   
54670   5.297636   5.566142   5.472700   5.762386   4.963139   5.634883   
54671   5.253165   5.978144   5.889662   6.222809   4.792429   6.156076   
54672   2.592453   2.700229   2.656674   2.719876   2.608102   3.063190   
54673   3.340522   3.633973   3.265097   3.625882   3.477362   3.603461   
54674   2.932932   3.271605   2.856124   2.958953   2.874971   2.932881   

          AJ_6_h   AJ_24_h   AJ_48_h  
0      10.223919  9.710350  9.465731  
1       9.000807  9.152421  9.467526  
2       8.169325  6.049426  5.657824  
3       7.859269  8.060785  8.116295  
4       2.961509  2.897476  3.059194  
...          ...       ...       ...  
54670   5.905186  5.537162  5.742731  
54671   6.191868  5.819676  6.084831  
54672   2.645845  2.834575  2.638259  
54673   3.616770  3.500324  3.598264  
54674   3.031149  2.981076  2.915787  

[54675 rows x 9 columns]

In [18]:
# Mengisi nilai yang hilang (jika ada) dengan nilai rata-rata kolom
df2 = df2.fillna(df2.mean())

#Normalize Data
import numpy as np
from sklearn import preprocessing
data3 = np.copy(df2)

# Standardisasi data dengan modul StandardScaler
scaler = StandardScaler()
df2_standardized = scaler.fit_transform(data3)
df2_std=pd.DataFrame(df2_standardized,columns=df2.columns)
df2_std

A_6_h    A_24_h    A_48_h     J_6_h    J_24_h    J_48_h    AJ_6_h  \
0      2.171238  2.084190  2.273095  2.076569  2.025677  2.109172  1.930957   
1      1.487372  1.654592  1.376889  1.535941  1.635127  1.366442  1.434627   
2      0.312272  0.101544 -0.009730 -0.043145 -0.165361 -0.195392  1.097218   
3      1.083024  1.011642  1.030172  0.914967  0.995594  1.066630  0.971400   
4     -0.975043 -0.982146 -1.025780 -0.992885 -0.985863 -1.082728 -1.016072   
...         ...       ...       ...       ...       ...       ...       ...   
54670 -0.070514  0.038196  0.001523  0.119905 -0.203825  0.065499  0.178449   
54671 -0.088563  0.204021  0.169565  0.306872 -0.272918  0.279129  0.294782   
54672 -1.168397 -1.115292 -1.133382 -1.115589 -1.156996 -0.988602 -1.144166   
54673 -0.864798 -0.739474 -0.888178 -0.747680 -0.805174 -0.767152 -0.750172   
54674 -1.030215 -0.885322 -1.053000 -1.018505 -1.048984 -1.042014 -0.987812   

        AJ_24_h   AJ_48_h  
0      1.714761  1.625978  
1      1.488914  1.626710  
2      0.232839  0.073560  
3      1.047026  1.075836  
4     -1.043052 -0.985857  
...         ...       ...  
54670  0.025478  0.108175  
54671  0.139838  0.247643  
54672 -1.068514 -1.157465  
54673 -0.799023 -0.766088  
54674 -1.009211 -1.044322  

[54675 rows x 9 columns]

##Save data bersih sudah std dan normal ke laptop

In [12]:
#Save data ke laptop
from google.colab import files
df2_std.to_csv("data_nomal&std.txt", index=False, encoding='utf8', header=False)
files.download('data_nomal&std.txt')
"done"

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

'done'

##Langkah 2 (Threshold)

In [20]:
#mencari nilai fold change
#menghitung rata-rata setiap kondisi
mean_A6 = np.mean(df2_std['A_6_h'])
mean_A24 = np.mean(df2_std['A_24_h'])
mean_A48 = np.mean(df2_std['A_48_h'])
mean_J6 = np.mean(df2_std['J_6_h'])
mean_J24 = np.mean(df2_std['J_24_h'])
mean_J48 = np.mean(df2_std['J_48_h'])
mean_AJ6 = np.mean(df2_std['AJ_6_h'])
mean_AJ24 = np.mean(df2_std['AJ_24_h'])
mean_AJ48 = np.mean(df2_std['AJ_48_h'])

# Menghitung fold change ekspresi gen A_6_h & J_6_h
fc1 = mean_J6 / mean_A6
# Menghitung fold change ekspresi gen  A_24_h & J_24_h
fc2 = mean_J24 / mean_A24
# Menghitung fold change ekspresi gen  A_48_h & J_48_h
fc3 = mean_J48 / mean_A48
# Menghitung fold change ekspresi gen  A_6_h & AJ_6_h
fc4 = mean_AJ6 / mean_A6
# Menghitung fold change ekspresi gen  A_24_h & AJ_24_h
fc5 = mean_AJ24 / mean_A24
# Menghitung fold change ekspresi gen  A_48_h & AJ_48_h
fc6 = mean_AJ48 / mean_A48
# Menghitung fold change ekspresi gen J_6_h & AJ_6_h
fc7 = mean_AJ6 / mean_J6
# Menghitung fold change ekspresi gen J_24_h & AJ_24_h
fc8 = mean_AJ24 / mean_J24
# Menghitung fold change ekspresi gen J_24_h & AJ_24_h
fc9 = mean_AJ48 / mean_J48

# Menghitung fold change ekspresi gen J_6_h & A_6_h
fc10 = mean_A6 / mean_J6
# Menghitung fold change ekspresi gen  J_24_h & A_24_h
fc11 = mean_A24 / mean_J24
# Menghitung fold change ekspresi gen  J_48_h & A_48_h
fc12 = mean_A48 / mean_J48
# Menghitung fold change ekspresi gen  J_6_h & A_6_h
fc13 = mean_A6 / mean_J6
# Menghitung fold change ekspresi gen  J_24_h & A_24_h
fc14 = mean_A24 / mean_J24
# Menghitung fold change ekspresi gen  J_48_h & A_48_h
fc15 = mean_A48 / mean_J48
# Menghitung fold change ekspresi gen AJ_6_h & J_6_h
fc16 = mean_J6 / mean_AJ6
# Menghitung fold change ekspresi gen AJ_24_h & J_24_h
fc17 = mean_J24 / mean_AJ24
# Menghitung fold change ekspresi gen AJ_24_h & J_24_h
fc18 = mean_J48 / mean_AJ48

fold_change = np.array([[[fc1, fc2, fc3], [fc4, fc5, fc6], [fc7, fc8, fc9]], 
   [[fc10, fc11, fc12], [fc13, fc14, fc15], [fc16, fc17, fc18]]])
print("ini nilai foldchange\n",fold_change)

ini nilai foldchange
 [[[ 0.5         4.          1.58823529]
  [-1.06818182  6.         -1.        ]
  [-2.13636364  1.5        -0.62962963]]

 [[ 2.          0.25        0.62962963]
  [ 2.          0.25        0.62962963]
  [-0.46808511  0.66666667 -1.58823529]]]


##Langkah 3 (Matriks Kuantisasi)

In [ ]:
#matriks kuantisasi

##Langkah 4 (Matriks Rank)

##Langkah 5 (Evaluasi Tricluster setiap skenario)

##Gene Ontology (GO)